version: "3.9"

services:
  # webアプリケーションのコンテナ
  app:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
      target: php82
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    working_dir: /var/www

  # webサーバーのコンテナ
  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www

  # dbサーバーのコンテナ
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: diary_sns_app
      MYSQL_USER: diary_sns_app_user
      MYSQL_PASSWORD: diary_sns_app_password
      MYSQL_ROOT_PASSWORD: diary_sns_app_password
      TZ: "Asia/Tokyo"
    volumes:
      - ./infra/db/data:/var/lib/mysql
      - ./infra/db/my.conf:/etc/mysql/conf.d/my.conf
      - diary-sns-app-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOSTS=db
      - PMA_USER=diary_sns_app_user
      - PMA_PASSWORD=diary_sns_app_password
    ports:
      - "3001:80"

  mail:
    image: axllent/mailpit:v1.8
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  diary-sns-app-volume:
